export async function shareShoppingList(items: any[]) {
  const text = items
    .map(i => `${i.category ? `[${i.category}]` : ''} ${i.name} — ${i.displayQty || (i.neededQty + ' ' + i.unit)}`)
    .join('\n');

  const shareData = {
    title: 'Shopping List — Meal Magic',
    text: `🛒 Shopping List\n\n${text}\n\nGenerated by Meal Magic`,
  };

  try {
    if (navigator.share) {
      await navigator.share(shareData);
    } else {
      await navigator.clipboard.writeText(shareData.text);
      alert('Shopping list copied to clipboard!');
    }
  } catch (e: any) {
    if (e.name !== 'AbortError') {
      await navigator.clipboard.writeText(shareData.text);
      alert('Shopping list copied to clipboard!');
    }
  }
}
